# Generated by Django 5.2.8 on 2025-11-14 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 11, 27)),
        ),
    ]
